### ISSUE TITLE
Many statblocks in `monsters.json` are missing the modifier for their `hit_dice` field

### ISSUE THREAD

**Issue by cynicaloptimist** [open5e/open5e-api#100]
https://github.com/eepMoody/open5e-api/blob/master/data/WOTC_5e_SRD_v5.1/monsters.json
A few examples include the Bandit and Knight statblocks, but any instance of the `hit_dice` field where there is no modifier is probably affected by this.

Improved Initiative uses the hit_dice field when rolling random monster HP so the modifier is important.
https://github.com/cynicaloptimist/improved-initiative/issues/580

Thanks!

**Comment by Gredelston** [comment]
Nice find, @cynicaloptimist. Thanks for reporting the issue.

It appears that our `WOTC_5e_SRD_v5.1/monsters.json` was missing modifiers for all beasts (ex. Wolf) and all NPCs (ex. Bandit). #132 should address this.
