### ISSUE TITLE
"Player's handbook" spells not in the Systems Reference Document

### ISSUE THREAD

**Issue by jypma** [open5e/open5e-api#112]
I realize the recent license adventure might make this a tricky question, but in general: There's a set of spells which are only present in the 5e "Player's handbook", and not in the "Systems Reference Document". For example, the [Blade Ward](http://dnd5e.wikidot.com/spell:blade-ward) cantrip. 

Would it be ok to add a json with the extra spells of the Player's Handbook (and perhaps other items) to this project? Most other wiki/collection sites do seem to have all those spells added in some shape or form.

**Comment by eepMoody** [comment]
Unfortunately, we are limited to only including those items published in an SRD under the OGL license. WotC has apparently decided we aren't allowed Blade Ward. :(
