### ISSUE TITLE
Add docstrings to files, classes, functions

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#115]
More and more devs are joining the project, thanks to the shout-out on SlyFlourish's podcast. As projects scale and gain contributors, style and documentation become increasingly important. Let's start by adding docstrings.That way, new contributors will know what they're doing, and they will be encouraged to document their own code, too.

I propose that we follow [PEP 8](https://peps.python.org/pep-0008/) for overall Python style and [PEP 257](https://peps.python.org/pep-0257/) for docstring conventions specifically.

**Comment by Gredelston** [comment]
I've started working on this on my fork. Also reordering imports in compliance with PEP-8, adding shebangs... simple style stuff.

**Comment by augustjohnson** [comment]
PEP8 has mostly been applied to the v2 app. 99% of relevant classes have docstrings. We're stalling dev on v1, so I think the intent of this is closed.
