### ISSUE TITLE
Bump Python version to 3.11

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#116]
Currently this project runs on python3.8, which is a legacy security release. The latest stable release is 3.11. If we upgrade to 3.11, we get access to all kinds of cool features, including:

* Better type hints
* Structural pattern matching (i.e., the `match` statement)
* Exception groups
* .toml parsing (useful for, say, if we want to start using [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/))
* Bunch of random new functions, like `str.removeprefix`
* Speed gains averaging 22%
* Devs won't have to install a legacy version of Python

**Comment by txtsd** [comment]
If there is any interest moving from `Pipfile` to a `pyproject.toml`, let me know and I'll submit a PR with documentation changes too. I will use `poetry`.

**Comment by augustjohnson** [comment]
Prod is running on 3.11 at this point, see here: 
https://github.com/open5e/open5e-api/blob/staging/Dockerfile#L1
