### ISSUE TITLE
Support passing multiple values for filtering

### ISSUE THREAD

**Issue by paullofte** [open5e/open5e-api#120]
To support a more advanced search API it would be great to be able to provide a list of attributes to filter on.

the example here would be asking for all monsters CR 1 & 2

/monsters/?challenge_rating=1&challenge_rating=2

another option would be searching for multiple types of monsters, or any other attribute that is a string

**Comment by eepMoody** [comment]
Interesting SO answer which provides a filter-based solution, and suggests the format: `/monsters/?challenge_rating=1,2,3`

https://stackoverflow.com/a/59379668

**Comment by augustjohnson** [comment]
This should be fixed more or less in #223. CR is now a float, and supports LT, LTE, GT, GTE and RANGE.

**Comment by augustjohnson** [comment]
This specific issue has been fixed. If you've got other attributes that are funky, let me know, but they've been refreshed since you looked at them.
