### ISSUE TITLE
Armor: Response lacks "base_ac" value.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#135]
The import file here includes "base_ac", "plus_dex_mod" and "weight" name/value pairs.
https://github.com/open5e/open5e-api/blob/master/data/WOTC_5e_SRD_v5.1/armor.json

These values are either missing or blank in the api response here:
https://api.open5e.com/armor/

**Comment by Gredelston** [comment]
`base_ac` and `plus_dex_mod` (as well as `plus_con_mod`, `plus_wis_mod`, and `plus_flat_mod`) get wrapped into the `ac_string` field, which is visible: for example, `base_ac=13, plus_dex_mod=True` becomes `ac_string="13 + Dex modifier"`. If you think users would benefit from seeing those internal fields, it's easy to display them, but I am curious to know why.

The weight thing is totally a bug, we should fix it.

**Comment by augustjohnson** [comment]
To use the API as a source for some programmatic calculations of AC and such, having the fields broken down into those low-level values would be nice.  I vote that we DO make them available as well as the ac_string field, which is a concat.
