### ISSUE TITLE
Implement a "random" api request

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#136]
For example:

If I make a request to monsters but include a argument that's something like random=1, then it returns 1 randomized monster that also meets the filter criteria.

**Comment by eepMoody** [comment]
I would wonder if this should be a different set of endpoints, because of how properties like "random" are likely to interact with other features of eg. the monster's endpoint like pagination, ordering, etc.

**Comment by augustjohnson** [comment]
I would definitely like some feedback on this design.  As of this moment, this branch just makes a new /spells/random endpoint that can consume all of the same variables.  We may want to exclude that endpoint from caching at the cloudflare layer.

**Comment by augustjohnson** [comment]
I will reimplement this if it turns out to be important. Closing for now, we can blow up the branch too.
