### ISSUE TITLE
Queryable mechanics, such as Abilities and Proficiencies

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#139]
See discussion thread on Discord: https://discord.com/channels/470638316103008268/1086682420704727110

Original request comes from @sturlen on Discord:
> Having a more structured way of getting rules data such as Ability Scores would be helpful building Character Sheets or VTTs. It would also make it easier to create links to specific rules for the Open5e website e.g `open5e.com/gameplay-mechanics/ability-scores#advantage-disadvantage`

Sturlen's primary usage example is mechanics for hover-tips on ability scores, such as (for Strength): `Measuring physical power.` We also thought it could be useful to do this for Proficiencies and Skills.

I propose that we add a new table `Mechanic`, like so:

```py
class Mechanic(models.Model):
    name: str
    slug: str
    category: str # Either "ABILITY", "PROFICIENCY", or "SKILL" (for now)
    brief_description: str
    parent_section: Section # To reference the longer rules
```

We can also expose separate API endpoints for `Ability`, `Proficiency`, and `Skill`, each of which queries this table with a filter on `.category`.

Thoughts:
1. Does it make the most sense to have `Mechanic` as one generic table, or should we instead have separate tables for `Ability`, `Proficiency`, `Skill`?
2. Should we have a separate `MechanicCategory` table to future-proof against changing category strings?
3. Is `Mechanic` an OK name? Are skills not also mechanics? Maybe `BasicMechanic`, `BasicRule`, something else...?
4. Do we need to update any other tables to reference these? For example, perhaps `CharClass` should reference the skills for the proficiency list.

**Comment by augustjohnson** [comment]
Related to #73. My vote is the more endpoints the merrier.
if you start digging you'll find some dirty laundry though, such as "Actions" fields beings stored in the database as json, and loaded at view time. Maybe the whole data model could be improved a cleaned up a bit?

**Comment by augustjohnson** [comment]
I think there is definitely a need for Ability as an endpoint.

There's probably a need for a Skill endpoint.

I can't reasonably see a need for Proficiency. That seems pretty open ended. Does Thieves Tools go in there? What about Nature? What about Heavy Armor? What about Unarmed Strikes? All of those things are mentioned as things that a character can possibly be proficient in, but they are all very different activities. I think we leave that off.
