### ISSUE TITLE
Set up automated unit tests

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#142]
I'm not even asking for full test coverage here. Here are my desiderata:

1. At least one unit test. That should be easy to write, right? Django makes automated tests easy to write and to run. 
2. Ensure that tests run during the CI check. (TBH this would be good for me to implement since I want to learn how our CI works.)
3. Bonus feature: Run tests as a preupload hook? I'm wary of making the upload too long, and it might be redundant with running during CI... but it also might be convenient for devs who don't want to get suddenly confused when their beautiful PR fails checks. But also, that's what CI checks are for. I'm conflicted about this part!

My main goal with this ticket is to get us _started_ so that we can easily add more tests in the future.

**Comment by Gredelston** [comment]
Later, I'll be interested in spinning up a test database. It's such a pain in the butt to test my code on the production database, since `quickload` takes so long. But, this is a prerequisite for that.

**Comment by Sturlen** [comment]
I think some data validation tests would be especially useful here, as the main sell of the project is to be able to access well structured data. These could probably run fast enough for a preupload hook. 

Unsure if it would be best to validate the API response, the data files or both.

**Comment by dprothero** [comment]
I wonder if we should decide on https://github.com/open5e/open5e-api/issues/148 first, since that would separate the data validation tests from the API functionality testing.

Either way, we should set up a GitHub Action to run the tests.

**Comment by dprothero** [comment]
OK, the GitHub Action is in place. See `.github/workflows/pr_validation.yml`. You'd want to add running the tests in there.

**Comment by augustjohnson** [comment]
You're too slow, I already added them :)
https://github.com/open5e/open5e-api/pull/181 see this.
Currently it ONLY tests an empty instance, and ONLY the Manifest endpoint, but it does it in 0.023 seconds lol.  I'd say let's get some tests on the empty instance written, then we can have a heavier test suite written out with some data in it.

**Comment by augustjohnson** [comment]
#198 mostly finishes this out. It at least tests the import from file to output flow pretty well.  Lots of other places that COULD be tested, but that's a biggie.

**Comment by augustjohnson** [comment]
We've got tests consistently running as part of every PR, and a solid framework for adding more.  I think we're good.
