### ISSUE TITLE
Set up API versioning

### ISSUE THREAD

**Issue by Gredelston** [open5e/open5e-api#145]
Alice uses the Open5E API to power her webapp, a virtual tabletop (VTT). Her webapp queries the API when it needs monster stats. It's stable and it works.

Bob is a developer for the Open5E API. He figured out a new way to organize the `Monster` table. He realized that the `challenge_rating` field would be better as a float rather than a string, so he created a new `cr` field. He wants to delete the old `challenge_rating` field. (Based on a true story: see #84)

Bob has two choices:
1. Delete the `challenge_rating` field. This will break Alice's VTT until she fixes it.
2. Leave the legacy `challenge_rating` field in there forever to prevent breaking Alice's VTT.

Neither of these options is great. Currently we prefer option 2 because we don't want to break our consumers. If we always do this, our code base will just accumulate tech debt forever. It will become increasingly confusing for both O5E developers and consumers.

There is another solution, which is for us to set up API versioning. In this case, events could transpire like this:
1. Open5E releases Version 1.0.0.
2. Alice pins her webapp to point to O5E Version 1.0.0.
3. Bob implements `cr` and merges it to O5E Version 1.0.1. He marks `challenge_rating` for deprecation.
4. Because Alice's O5E integration is stable, she doesn't pay attention to the new O5E release. She stays pinned to 1.0.0, using the now-deprecated `challenge_rating` field.
5. Some time later, the O5E API gets ready to release Version 2.0.0. Bob deletes the deprecated `challenge_rating` field. This is a breaking change, but that's OK because this is a "major release". Alice is unaffected by this deletion, since she's still pinned to 1.0.0.
6. Some time later, Alice decides she wants access to some cool new O5E API features. She wants to upgrade to O5E Version 2.0.0. At first, she naively tries to just change the API version number in her app config, but she gets test failures for the deleted `challenge_rating` field. She checks the release notes and sees that this field was deleted. Alice starts using the `cr` field, then updates her app config. Her VTT experiences no downtime.

Obviously, there's a lot to think through for implementing this feature. Hopefully this story makes it a little easier to understand the need.

Some questions that come to mind...
1. What versioning scheme do we want to use?
2. What kinds of features are OK to put into a major release vs. a minor release vs. etc?
3. Are we going to hit storage problems with hosting different versions of our entire database?
4. Can consumers still subscribe to the nightly build or to tip-of-tree if they want bleeding-edge features?
5. Who is going to write release notes? How will we manage the information that needs to go into that?
6. What API version should our website point to? Do we need to set up a website versioning scheme, too?

**Comment by augustjohnson** [comment]
**Proposal:**
Only the API is versioned, the data is a distinct product.

Move current API to /v1/monsters/. (along with other endpoints).
Create alias from /monsters to /v1/monsters/. Alias could be a 200 reply with rewritten "next" field.
Move over the website to use /v1/ because it'll be an example. Move all other documentation over to /v1/.
Current process allows for addition of API fields and addition of query parameters however we want.  No breaking changes.

When we arrive at a breaking change, make the new API available at:
/v2/monsters/

The API version does not have anything to do with the DATA version though. Those are distinct.

**Comment by Gredelston** [comment]
@augustjohnson That's an interesting proposal. I think this split would add nontrivial complexity, since the data is so deeply related to the code that interprets and exposes that data.

Thinking about the example story I wrote above, if we extracted DATA, could Bob ever delete the `challenge_rating` field from JSON without breaking users who are pinned to v1.0.0? I suppose that would be possible if each API release were pinned to a specific hash of the DATA repo. Is that what you're envisioning?

**Comment by txtsd** [comment]
The hash idea is fine, but we should probably version the data together with the API. Then testing and additions would (obviously) be done on a master/main/dev branch.

**Comment by Sturlen** [comment]
Keeping separate data sources for each version would be an effective method to guarantee that older APIs don't break due to changes in data. 

The question then is: should older API's expect having access to new content? If I was in the shoes of a VTT author like Alice, then having a stable API would my main concern, rather than the content. Changing and validating changes on multiple versions would also be an extra burden for maintainers.

**Comment by augustjohnson** [comment]
Hold up, I see this conversation as the one about API versioning, not data versioning. Data versioning discussions can be done here: https://github.com/open5e/open5e-api/issues/148. 

An API version should only increment when the original contract for the API has changed in a breaking way. I would say our current "contract" is pretty flexible so as long as we keep the tenet of "don't change field names or parameter names" we can add new endpoints and fields. This should allow us to stay on the current contract of our API for quite a while.

Eventually, (as a ridiculous example, let's say everyone wants to use XML) we may find a need for a breaking change. If we come across a breaking change, then we should consider adding a distinct API version, for example, v2. This is commonly done in the path of the API.  "V1" maintains functionality, V2 adds functionality (XML let's say).

My proposal is to change the current uri scheme (api.open5e.com/monsters/) to include a version (api.open5e.com/v1/monsters/) with the idea that it would be easier to add a v2 in the future.

I do not see a reasonable need for this at this time though.  Regarding data versions, I have some thoughts in the other thread.

**Comment by Gredelston** [comment]
Hey look, the Django REST Framework has documentation on versioning. https://www.django-rest-framework.org/api-guide/versioning/

**Comment by augustjohnson** [comment]
FYI #248 appears to pretty much resolve this. Working on a review.

**Comment by augustjohnson** [comment]
Versioning as a concept has been added.
