### ISSUE TITLE
Add environment tags to monsters

### ISSUE THREAD

**Issue by StraubJones** [open5e/open5e-api#146]
Jump in to the discord thread to discuss more: [thread](https://discord.com/channels/470638316103008268/1082021546257817820)

Might also eventually want filtering by this on the UI, might make be good to make a project to sync across front/back end

**Comment by StraubJones** [comment]
Go ahead and add environment tags to the Google sheets here: [sheets](https://docs.google.com/spreadsheets/d/1v4OOox2Yvy72dBNwGKzP_fck7JZIud1nlwvGdC-qZAc/edit?usp=sharing)

We've eventually fold it back into the data set.

**Comment by augustjohnson** [comment]
This is partially addressed in #245. Keep an eye on that.

**Comment by augustjohnson** [comment]
Fixed in #245 which is in production.
