### ISSUE TITLE
Rewrite quickload.py and quicksetup.py as shell scripts.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#147]
in api/management/commands/ there are two files that are basically just shell scripts. They should be actually re-written as shell scripts. It's probably safe to assume development will be occurring on something with bash at this point. These files were originally written to assist windows developers.

Using python to launch python for this purpose is a bit of a round peg square hole type thing, and should be avoided.

README.md would have to be adjusted.
Dockerfile could potentially be adjusted to take advantage of quickload, although this is not required at the moment.

**Comment by Gredelston** [comment]
I actually disagree with this. Bash is harder to read, to test, and to modularize. IMO bash is best for prototypes that should be converted into more robust languages.

I do agree that using Python to invoke Python is an anti-pattern. I have an open PR in need of approval, which addresses this anti-pattern by replacing those subprocesses with Django's call_command, which is built for exactly this use case.

**Comment by Gredelston** [comment]
> I have an open PR in need of approval, which addresses this anti-pattern by replacing those subprocesses with Django's call_command, which is built for exactly this use case.

That was #133, which is now closed.

**Comment by augustjohnson** [comment]
Agreed. This is better. Closing this.
