### ISSUE TITLE
Add a swagger schema file.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#153]
https://www.django-rest-framework.org/api-guide/schemas/

Suggested by @Dashron on the discord.

**Comment by Dashron** [comment]
I've got the basics for this working, but the title output sucks and it's a limitation of the built in generator. It looks like I should be able to override it so I'm working on that still. Will drop a message when it's resolved

**Comment by Dashron** [comment]
Finally had some time and figured out the code side of this. I just need to figure out how to distinguish between singular and plural endpoints on the views, and then start writing titles for everything.

**Comment by augustjohnson** [comment]
This is live at https://open5e.readme.io/reference/listfeats (e.g)! woohoo!

**Comment by Dashron** [comment]
Looks great!
