### ISSUE TITLE
[DATA BOUNTY ] - Classes and subclasses from Level Up Advanced 5e

### ISSUE THREAD

**Issue by mshea** [open5e/open5e-api#162]
Level Up Advanced 5e has several classes not included in the 5e SRD along with dozens of subclasses that the 5e SRD lacks. Integrating these classes and subclasses into Open 5e could make it very useful for external character builders looking for alternative sources.

https://a5e.tools/rules/adventuring-classes

https://a5e.tools/rules/archetypes

**Comment by augustjohnson** [comment]
There's some stuff to unpack here.  While we have support for new, custom classes, a significant portion of what we consider the "fighter" (from the SRD) is in a big old markdown-based text field labeled "desc".

**Options (roughly in order of how difficult they would be):**
1. Make a distinct "a5e fighter" class. (this is my preference). The new archetypes (like bladeseer) would ONLY tie to the a5e classes.
2. Functionally replace the existing "fighter" to include a5e stuff, including new stuff like the "Technical Fighting" fighting style, and Knacks.
3. Modify the data model to include a "fighting style" table and adjust options based on the "documents" you're viewing from. Various other new data fields may be necessary... Knacks, Maneuvers, etc.

**Comment by mshea** [comment]
Great thoughts. I tend to lean towards whatever's easiest but I recognize that things we do now could hose things up later if we decide to change them.

**Comment by augustjohnson** [comment]
Per this site: https://a5esrd.com/a5esrd the a5e classes are not yet released under the CC (or OGL) licenses. So I think it's a bit premature to add them in.

**Comment by augustjohnson** [comment]
Adventuring classes ARE now posted there, including subclasses.
