### ISSUE TITLE
Consider adding detailed code version information in an API response

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#166]
As a consumer of the API, I'd like to have a good  understanding of exactly the source code that was used to present the API that I'm consuming.

Brainstorming some options:
Response header that includes a long-form version (full semantic version, maybe including build?)
> We don't have a reliable versioning system at the moment, this would have to be designed.

Response header that responds with a specific commit hash?

/version endpoint which offers up some data about the API.  This could be in the form of the manifest endpoint, which is very helpful.

**Comment by Sturlen** [comment]
I'd be satisfied with current and latest API version in the Response object. I usually use libraries to handle stuff like headers and response type, so I much prefer all the important data be in the payload itself. Details of version will likely have to wait for #145 to be decided on first though.

Having a data version or hash could be interesting, but details about source files would be too much. It shouldn't matter to consumers of the API if we replaced the entire backend, as long as we hold up the API contract (which as this point should probably a real document).

**Comment by eepMoody** [comment]
I like the idea of including a commit hash; it's short but very informative if the person has questions about the source code.

Though I don't really know how to set that up. Maybe that's something a Github Action could take care of?

**Comment by Sturlen** [comment]
> Maybe that's something a Github Action could take care of?

There is in fact an Action for this: https://github.com/marketplace/actions/commit-hash

You could run on as part of the CI/CD pipeline and add the hash as an environment variable. This would then be used by Django to insert the hash into each response.
