### ISSUE TITLE
What should be done when two sources contain the same entity?

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e-api#168]
Example: WotC's Fighter and Level Up's a5e Fighter. This specific example came up in #162 and here are the options that were discussed:

> **Options (roughly in order of how difficult they would be):**
> 1. Make a distinct "a5e fighter" class. (this is my preference). The new archetypes (like bladeseer) would ONLY tie to the a5e classes.
> 2. Functionally replace the existing "fighter" to include a5e stuff, including new stuff like the "Technical Fighting" fighting style, and Knacks.
> 3. Modify the data model to include a "fighting style" table and adjust options based on the "documents" you're viewing from. Various other new data fields may be necessary... Knacks, Maneuvers, etc.

_Originally posted by @augustjohnson in https://github.com/open5e/open5e-api/issues/162#issuecomment-1478061958_

**Comment by Gredelston** [comment]
To clarify, I believe two sources here would contain **different versions of** the same entity.

I agree with August's preference: make a distinct a5e fighter class. I think that's the easiest way for folks to only view the content they want to use. For example, I'm sticking with SRD in my campaign; I want to link my players to the Fighter page without them seeing a5e content.

If you want to use the Bladeseer archetype, then you know what "A5E Fighter" refers to and you know to click on that page.

**Comment by eepMoody** [comment]
Of these, 1 seems like the most viable.

a5e hasn't generally replaced 5e, so I don't think we can just overwrite the official class, and it would be very confusing for a player or DM to have to sift between both on the same page to figure out what applies.

**Comment by Sturlen** [comment]
I agree with option 1. as well, but should the A5e Fighter just be called `Fighter` and be distinguished by the document slug or should the name be modified to specify `a5e Fighter`?

I think versions with the same name would work best, but I'd like to hear your opinions on it as well.

**Comment by Gredelston** [comment]
In my opinion, they should have distinct names. Consider for example the Open5E Website: 
![image](https://user-images.githubusercontent.com/1417909/227256614-b938608c-d15d-4d7d-8f0f-6d42d3ceb0b4.png)

We want to display each class with a distinctive name. If we have multiple lines that read `Fighter`, it's unclear what to click on. As a workaround, the Open5E website could display the name + the source document, like `Fighter _(WotC_SRD_v5.1)_` and `Fighter _(a5e)_`. But I would prefer not to surprise all of our users with that bug when we have an easier fix available.

IMO, the name should be a human-readable unique identifier.

**Comment by augustjohnson** [comment]
That's a toughie. I tend towards 
"The name field in the API is the name that the original document specifies" 

I'd definitely say there's some UI stuff that needs to be clarified. And I would say that the slug should append the document source slug upon collision.

Maybe this UI layer doesn't get resolved until we have a good solution for user-based filtering for sources, and the UI for THAT resolves this particular issue.

**Comment by Sturlen** [comment]
I like the idea of adding the document slug to the slug of the entity, because currently there is currently no way to uniquely identify one entity. Though for now this would have to be done only for new content, to not break backwards compatibility.

I'd also prefer to leave the name alone and let users decide can how to display content from different sources. As an example, open5e already uses tags for monsters:

![image](https://user-images.githubusercontent.com/43607012/227341651-ec5d9c76-d5ff-4302-bbb4-6f040cdf1ae6.png)

**Comment by mshea** [comment]
Should every item have a source tag to identify where it's from? Monsters have that, right?

**Comment by Gredelston** [comment]
All `GameContent` (such as monsters, spells, armor, etc.) have a foreign key to the Document that they come from: https://github.com/open5e/open5e-api/blob/master/api/models.py#L47

**Comment by Sturlen** [comment]
Continuing to use `document__slug` to differentiate variants of the same GameContent appears to be the best option.
