### ISSUE TITLE
/items endpoint

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#169]
The proposal is simple: Let there be an items endpoint that returns many different type of items, for example, both Cloak of Shadows and Light Crossbow.

The implementation is difficult. Implementation suggestion:
Create a new Items model that has fields like:
name
weight
cost
type(?)

Use multi-table inheritance to implement the /weapons endpoint.
https://docs.djangoproject.com/en/4.1/topics/db/models/#multi-table-inheritance

**Comment by augustjohnson** [comment]
poisons, tools, traps are all potential sources of data too.

**Comment by Gredelston** [comment]
I like it. I think `type` should be a [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) (new in py3.11!), with stringy values like "ARMOR", "MAGICITEM", "MOUNT", etc.

**Comment by augustjohnson** [comment]
This is handled in #302 .

**Comment by augustjohnson** [comment]
This has been pushed to beta.
