### ISSUE TITLE
Remove some redundant, confusing files from the root.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#188]
The following files are redundant, confusing and I don't think they're used for anything at all. I propose we delete them all!

1. /.python-version - not accurate.
2. /requirements.txt - we use the pipfile only
3. /runtime.txt - not accurate.
4. MAYBE .env?  It definitely should have some adjustments to be a more clean repo.
5. /heroku.yml - no longer used.
6. /.vscode - This appears to be for ean's local machine lol.

I think there may be a better home for /startup-script.sh as well, maybe under scripts? Not sure.

@dprothero I'm interested in your input on this for sure.

**Comment by dprothero** [comment]
LGTM

**Comment by dprothero** [comment]
I think .env is necessary during the docker build for the manage.py commands to be able to run. It just needs something with dummy values, as the Dockerfile removes the .env file after all the data is imported and before gunicorn is launched.

We could refactor the Dockerfile to not need the .env file, which would probably be ideal.

**Comment by augustjohnson** [comment]
Yes, I think that's a much better approach.

**Comment by Gredelston** [comment]
SGTM. For `.vscode`, let's just add it to the `.gitignore` so we don't ruin Ean's life.

**Comment by augustjohnson** [comment]
This is good to go after #200
