### ISSUE TITLE
Add AND/OR operators for searching resources

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#19]
Eg.

> So that you can find spells that are in common with two classes like "wizard+bard", in either of two classes like "wizard,bard" and in one class but not the other "-wizard,bard"

**Comment by augustjohnson** [comment]
I believe this would be accomplished by adjusting the filters for the spell lookup:

https://www.django-rest-framework.org/api-guide/filtering/#setting-filter-backends

**Comment by augustjohnson** [comment]
As an FYI, there is the ability to search based on added fields.  For example:
spells/?search=cleric is configured to search the 'dnd_class' model field. That results in 340 spells which all include cleric as a class.
Additionally there is the "contains" operator, which is a bit more specific.
spells/?dnd_class__icontains=cleric
There's also the 
http://localhost:8000/spells/?dnd_class__in=Cleric,Bard
Which only accepts full (case sensitive) values of dnd_class in this case, and may be missing some results regardless.  It appears to combine the comma-separated values with an OR though, but that's a little wonky.

**Comment by augustjohnson** [comment]
Ok this specific example, being able to filter on one class (which we've renamed to spell_list) and exclude items that match another list has been added to #222 in the form of:
spell_lists=bard&spell_lists_not=wizard.  Each field's exclusion requires a custom one-liner being added to the filterset, so if you can specific which fields this is desirable for, we can add them. After #222 gets merged, I'm going to close this specific example though.

**Comment by augustjohnson** [comment]
Ok, this is delivered on staging. Closing this out.
