### ISSUE TITLE
Convert material from Kobold Press's Tome of Heroes

### ISSUE THREAD

**Issue by mshea** [open5e/open5e-api#203]
Much of the material from Tome of Heroes is released under the OGL and is fully 5e compatible. This would fill out a lot of areas such as:

- subclasses
- feats
- backgrounds

Spells are largely covered by Deep Magic which is already in Open 5e. 

Extra credit for non-magic items. There's a lot of new mundane items in Tome of Heroes.

I think it'd be a good way to get a lot of new usable material into Open 5e.

If someone's willing to start taking a crack at converting the data, I'm happy to pay for a copy of the PDF to do so.

**Comment by eepMoody** [comment]
As of today, all this content has been added except for subclasses and subraces.

We will require some major development updates to cover the remainder, so I'm going to split this out into a few smaller issues!
