### ISSUE TITLE
When using djangos runserver, errors appear related to unsorted lists.

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#225]
...../home/august/.local/share/virtualenvs/open5e-api-r5PZvzh6/lib/python3.10/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.models.Weapon'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)

These appear to be related to usage of get objects all without an order_by.

**Comment by eepMoody** [comment]
What do we think for a default order here. `slug` maybe? I feel like listing monsters by alphabetical order is a pretty typical use-case absent an explicit selection.

**Comment by augustjohnson** [comment]
We have ordered lists now.
