### ISSUE TITLE
Explicitly exclude certain gamecontent items from being PRed

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#247]
Wizards' OGL has a specific callout for a set of gamecontent items that are not and will not be OGL. I think it would be a good idea to prevent the inclusion of these by a well-meaning, but errant committer.

I think the basic idea is "grep anything in /data for this content, and fail loudly upon finding it"

**Specific text:**
The following items are designated Product Identity,
as defined in Section 1(e) of the Open Game License
Version 1.0a, and are subject to the conditions set
forth in Section 7 of the OGL, and are not Open
Content: Dungeons & Dragons, D&D, Player’s
Handbook, Dungeon Master, Monster Manual, d20
System, Wizards of the Coast, d20 (when used as a
trademark), Forgotten Realms, Faerûn, proper
names (including those used in the names of spells
or items), places, Underdark, Red Wizard of Thay,
the City of Union, Heroic Domains of Ysgard, Ever-­‐‑
Changing Chaos of Limbo, Windswept Depths of
Pandemonium, Infinite Layers of the Abyss,
Tarterian Depths of Carceri, Gray Waste of Hades,
Bleak Eternity of Gehenna, Nine Hells of Baator,
Infernal Battlefield of Acheron, Clockwork Nirvana
of Mechanus, Peaceable Kingdoms of Arcadia, Seven
Mounting Heavens of Celestia, Twin Paradises of
Bytopia, Blessed Fields of Elysium, Wilderness of the
Beastlands, Olympian Glades of Arborea, Concordant
Domain of the Outlands, Sigil, Lady of Pain, Book of
Exalted Deeds, Book of Vile Darkness, beholder,
gauth, carrion crawler, tanar’ri, baatezu, displacer
beast, githyanki, githzerai, mind flayer, illithid,
umber hulk, yuan-­‐‑ti.

**Comment by mshea** [comment]
It's worth noting that the CC BY version of the SRD has no such restrictions. This is one of the few times that a company has put in product identity into the OGL it forbids you to use that you might otherwise be able to use. Anything trademarked, is, of course, off the table. Things like "mind flayer" is a bit fuzzier being two common words.

**Comment by augustjohnson** [comment]
Yeah this should probably be a manual check for data additions.  We did happen to catch a product identity issue with nord games stuff recently, so I think the process we have in place works, and it's tough to automate.
