### ISSUE TITLE
Determine requirements for new v2 API

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#251]
This is not a coding task.

Before we begin development, we should establish a clear set of requirements. What do we want the new API to do? What should it deliver? 

We should record those here, and then proceed to stubbing out contracts for discussion.

**Comment by augustjohnson** [comment]
Alternatively: crib everything from:
https://alchemyrpg.github.io/slate/#api-documentation

**Comment by augustjohnson** [comment]
I'm not convinced that Alchemy's format is the way to go, but they do appear to be releasing some of their content fairly openly.
https://github.com/alchemyrpg/5e-srd - this is a repo of .json files (including an _all.json) file of the entire wotc-srd in alchemy format.
Basically the _all.json file could be both the input, and the response of a new /characters endpoint.
I think there's a commitment from them to release stuff like spells and such openly too. They aren't a content creator, they are just a VTT.

**Comment by augustjohnson** [comment]
https://github.com/foundryvtt/dnd5e/tree/master/packs/src - this is Foundry's json input.

**Comment by augustjohnson** [comment]
Ok here's a few features that may be desirable for a v2.
1. Permissive import input formats. If a content creator has created a module for FoundryVTT, their onboarding process to Open5e is simple, basically just an import.
2. Easy-to-correct and modify state-based storage. If there's literally and error in the data, it's pretty simple to diagnose and find, and then correct.
3. Variable output formats. If a content creator WANTS to create a Foundryvtt module, and already has their data in open5e, then they can simply export, or maybe make an API call for that data.

We would need to ensure our data models can support multiple output formats, that's something that's not simple, but we'd be in control of that.

**Comment by augustjohnson** [comment]
All types of spells are included.
api.open5e.com/v2/spells/?name__icontains=magic <- a list of spells
api.open5e.com/v2/spell/wotc-srd/magic-missile <- a singular spell
api.open5e.com/v2/spellsets/ <- a list of spell sets, which are collections of spells.
api.open5e.com/v2/spellset/a5e/wizard <- a singular spell set

Items includes magic items, weapons, armor, etc.
api.open5e.com/v2/items/?cost__lte=10gp
api.open5e.com/v2/item/wotc-srd/adamantine-plate
api.open5e.com/v2/itemsets/ <- a list of item sets.
api.open5e.com/v2/itemset/wotc-srd/weapons <- a singular item set

This is non-player characters and monsters both.
api.open5e.com/v2/characters/
api.open5e.com/v2/character/a5e-srd/goblin
api.open5e.com/v2/charactersets/
api.open5e.com/v2/characterset/a5e-srd/monsters

This is backgrounds for characters.
api.open5e.com/v2/backgrounds/
api.open5e.com/v2/background/a5e-srd/goblin
api.open5e.com/v2/backgroundsets/
api.open5e.com/v2/backgroundset/a5e-srd/adventurers-guide

api.open5e.com/v2/feats/
api.open5e.com/v2/feat/wotc-srd/grappler

api.open5e.com/v2/conditions/
api.open5e.com/v2/condition/wotc-srd/stunned

Lowest priority - maybe could be redone? - Planes could maybe be included.
api.open5e.com/v2/sections/
api.open5e.com/v2/section/wotc-srd/diseases

My draft for URL paths. Feedback requested.
A class is always represented with all of it's subclasses.
api.open5e.com/v2/classes/
api.open5e.com/v2/class/a5e-srd/herald
api.open5e.com/v2/class/a5e-srd/herald/subclasses/?name__icontains=holy
api.open5e.com/v2/classsets/
api.open5e.com/v2/classset/a5e-srd/adventurers-guide

A race is always represented with all of it's subraces.
api.open5e.com/v2/races/
api.open5e.com/v2/race/a5e-srd/birdfolk
api.open5e.com/v2/racesets/
api.open5e.com/v2/raceset/a5e-srd/adventurers-guide

**Comment by eepMoody** [comment]
Another design note: Races currently have "traits" as a single blob of Markdown regardless of number of traits.

We should probably break these up into individual objects, and scour our JSON for other items that could be decomposed into more useful chunks.

**Comment by eepMoody** [comment]
@augustjohnson 

> All types of spells are included. 
> api.open5e.com/v2/spells/?name__icontains=magic <- a list of spells 
> api.open5e.com/v2/spell/wotc-srd/magic-missile <- a singular spell 
> api.open5e.com/v2/spellsets/ <- a list of spell sets, which are collections of spells. 
> api.open5e.com/v2/spellset/a5e/wizard <- a singular spell set

One thing that this appears to make tricky is getting info if you _don't_ want it from a single specific source, or you want a mix of sources. Thinking about this from the consumer side, ideally there should be something like `spellset/wizard` that I can filter down from there. (same pattern for other items)

**Comment by eepMoody** [comment]
I'll also raise again the idea of "ruleset" to replace the `source` parameter in those URLs.

Source is probably more specific than is needed, and seems like something better handled with filters. But there should only be one "Magic Missile" per "version" of D&D. (and I think we can/should make the editorial call to use the "most official" version if there's ever two of the same thing)

**Comment by augustjohnson** [comment]
FYI I am working on items, and the various related endpoints for v2. Currently this includes
- [ ] single concept of "weight" for all objects, characters, items, etc.
- [ ] single concept of "size" as well
- [ ] various shared "item" concepts, like cost and is_magical.
- [ ] implementations of weapon_type (which an item would have) and armor_type.

I've made a few decisions that will likely have impacts in other models, but this is pretty beta at the moment. Lots of new concepts brewing here. I'll actually have an endpoint or a few in maybe a week or so.

**Comment by augustjohnson** [comment]
https://github.com/open5e/open5e-api/tree/api_v2_items is the branch.

**Comment by augustjohnson** [comment]
Ok i'm closing this one out.  Classes is the only big missing piece, and I've got a solid tack on how to deliver that.
