### ISSUE TITLE
Improve importer for races to handle several new cases

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#267]
Based on issues discovered during the attempt to get the data @JonathanELawrence  created in https://github.com/open5e/open5e-api/pull/259 imported.

- Mechanism for adding a subrace to a race from a different source
- Ability to accept a subrace with no explicit speed (base it on the base race in this case)
- Ability to accept a subrace with no ASI (can be blank in this case)
- Ability to set variable ASI (currently using "Any" but cases like "Any but Constitution" exist and not sure how to represent that)

(@augustjohnson this last one relates to one of the design topics you brought up for the v2 API, on standardizing how we represent ASIs globally)

A good test of this and datasource to work with would be cherry picking in the info from https://github.com/open5e/open5e-api/pull/259/commits/5810b2ad0453b77811721b94b3167827d4e2eb67 and ensuring that all the subraces correctly import.

**Comment by augustjohnson** [comment]
So the design of v2 addresses a lot of this:
https://api-beta.open5e.com/v2/races/
1. Adding a subrace to a race from a different source should be no problem.
2. No base speed should not be an issue either, it's all a "trait" which is a child object.
3. Same.
4. Description of the trait is text-based, so this should be fine as well. It's not ready for a VTT exactly, but it's good.
