### ISSUE TITLE
Update search endpoint to allow content filters

### ISSUE THREAD

**Issue by eepMoody** [open5e/open5e-api#282]
In order to address https://github.com/open5e/open5e/issues/408 on the UI side, search needs to accept filters.

At a minimum, it should allow `document_slug__in` type filtering, which is used for source selection. Allowing the ability to retrieve only a count or limited fields would also be valuable.

**Comment by augustjohnson** [comment]
This is going to be replaced by #428 which should reasonably have these filters.
