### ISSUE TITLE
Add Kobold Press Player Races

### ISSUE THREAD

**Issue by s520864** [open5e/open5e-api#283]
Kobold Press has some player races that fall under their OGL, maybe other publishers do the same thing? Since we have stuff from "Tome of Beasts" why not include other stuff besides Monsters that fall under OGL, like "Classes", "Subclasses", "Spells", and "Races"?

Source: http://kpogl.wikidot.com/

**Comment by augustjohnson** [comment]
KPOGL is not a reliable source for kobold press OGL data.
That being said, Races, Spells, and many creatures have been added.
I have added a particularly juicy source of good KP data as a request here:
#514
