### ISSUE TITLE
V2 classes

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#296]
Use this as inspiration for the actual responses.
https://github.com/bradyslot/dndex/tree/master/src/data

**Comment by augustjohnson** [comment]
He's moved on to use Rust instead, but here's an example json object for a class:
https://github.com/bradyslot/dndex/blob/fac806e7d66757540299a861c683d20284fe1f02/src/data/classes/warlock.json

**Comment by augustjohnson** [comment]
#407 addresses this.

**Comment by calumbell** [comment]
With #407 merged to staging this issue has been resolved. I am going to go ahead and close it
