### ISSUE TITLE
When searching for feats it always returns every feat

### ISSUE THREAD

**Issue by JeremyMees** [open5e/open5e-api#301]
I make this api call `https://api.open5e.com/feats/?limit=20&search=slasher&page=1`
And it returns all the feats instead of filtering them on name. I use the same logic for every type and i only have problems with the feats.

**Comment by augustjohnson** [comment]
I can't find a simple reason for this:
Research done:
Tried to recreate the issue locally: Failure
Tried to recreate this issue on a few different models: Fail
Read up on:
https://www.django-rest-framework.org/api-guide/filtering/#searchfilter
- Search should NOT be behaving this way from what I can tell.
Confirmed search_fields are set correctly.
https://github.com/open5e/open5e-api/blob/staging/api/views.py#L261

So from what I can tell this is a caching issue, and my prediction is that cloudflare is set up in a funky way with the ?search query param... but I'm not certain. I don't have access to cloudflare, so I'll have to ask @eepMoody to take a look.

**Comment by augustjohnson** [comment]
Checking back on this:
The original error scenario of https://api.open5e.com/feats/?limit=20&search=slasher&page=1 no longer seems to return ANY results. In fact, I can't seem to find a feat named slasher at all in our history? I'm guessing that this can reasonably closed as couldn-not-recreate :/  Sorry!
