### ISSUE TITLE
Magic Item - Giant Fly

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#39]
There's a data issue with the figurines of wondrous power in the 5e magicitems.json.

https://open5e.com/magicitems/giant-fly

https://github.com/eepMoody/open5e-api/blob/master/data/WOTC_5e_SRD_v5.1/magicitems.json#L455

It should be simple to just update the data object, but there may be some formatting that needs to be adjusted and tested.

**Comment by shadowedlucario** [comment]
Looks like there was an attempt to fix this https://github.com/eepMoody/open5e-api/pull/43. It doesn't look like the API has been updated to include this fix. @eepMoody Does the API get updated automatically on new pushes to the repo or does it pull from some db somewhere that overwrites the data in `data/`?

**Comment by Gredelston** [comment]
This issue appears to be resolved. Looking at the website, https://open5e.com/magicitems/figurine-of-wondrous-power now shoes Giant Fly correctly, whereas https://open5e.com/magicitems/giant-fly does not show any results. Let's close this issue out.
