### ISSUE TITLE
Dwarf, Elf and Halfing should belong to the WotC SRD, but are listed as o5e originals

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e-api#390]
The [Races API route](https://api.open5e.com/v1/races/) returns several races referencing the wrong document. afaik it only happens to the Dwarf, Elf and Halfling race.

Since the same thing can be spotted in an [approval test](https://github.com/open5e/open5e-api/blob/5ad47ab552613292f2a0fe0040a6705e414aadc8/api/tests/approved_files/TestAPIRoot.test_races.approved.json#L21) made before V2 was merged, it's likely that the issue has been ongoing for some time.

My current theory it that this is related to adding open5e original subraces to existing races, since the o5e [races.json](https://github.com/open5e/open5e-api/blob/5ad47ab552613292f2a0fe0040a6705e414aadc8/data/open5e_original/races.json) references the Dwarf, Elf and Halfling race, even if it only adds a halfing subrace. This seems to have been imported in the [V2 api](https://github.com/open5e/open5e-api/blob/staging/data/v1/o5e/Race.json), which appears to have these races listed as original creations.

I've not yet had a chance to run any more tests on this, but removing the o5e Race.json file might work.

**Comment by Sturlen** [comment]
I tried removing `data\v1\o5e\Race.json` to the following result:
```
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'api_subrace' with primary key 'stoor-halfling' has an invalid foreign key: api_subrace.parent_race_id contains a value 'halfling' that does not have a corresponding value in api_race.slug.
```
I believe this happens because the Stoor Halfling, an Open5e original subrace, requires the Dwarf race to be defined in the same document. Unsure how to fix this in the new V2 system. Could you take a look at this @augustjohnson ?

**Comment by augustjohnson** [comment]
Good find, and you're almost there for the fix.
The old import logic re-cited the document for anything listed here as the parent (in this case, incorrectly, open5e).https://github.com/open5e/open5e-api/blob/main/data/open5e_original/races.json

When I used the existing database as my template for the new data format, I propogated that error, so my /data/v1 folder had the error in it.

The fix will be to:
1. Take the contents of /data/v1/o5e/Race.json and copy them (into a valid JSON list) into /data/v1/wotc-srd/Race.json
2. Delete /data/v1/o5e/Race.json.

**Comment by augustjohnson** [comment]
This is fixed on staging now.
https://api-beta.open5e.com/v1/races/halfling/
