### ISSUE TITLE
Sorting Issue: Incorrect Order when Sorting Monsters by Size

### ISSUE THREAD

**Issue by uribracha2611** [open5e/open5e-api#399]
**Issue:**
When attempting to sort monsters by size using the Open5E API, there is an inconsistency in the sorting order. Currently, when sorting in descending order, the first results include "Titanic" monsters, followed by "Tiny" monsters, which deviates from the expected sorting order.

**Steps to Reproduce:**
    Use the API endpoint for sorting monsters by size in descending order: [https://api.open5e.com/monsters/?ordering=-size](https://api.open5e.com/monsters/?ordering=-size)
    Observe that the first results include "Titanic" monsters, but instead of continuing in descending order, the subsequent monsters are "Tiny."

**Expected Behavior**:
When sorting monsters by size in descending order, the expected order should be from the largest size category ("Titanic") to the smallest size category ("Tiny") according to the standard D&D size classification.

Note:
If I'm using the API incorrectly, please clarify the correct usage. However, if this is indeed a bug, I am willing to try to solve it and submit a pull request.

Thank you for your assistance!

**Comment by Sturlen** [comment]
This is because the API lacking any awareness for what "size" classification means in D&D and is just sorting alphabetically. A possible solution is to add a new numeric field e.g. `size_rating` where a tiny creature is 0, small is 1, and so forth. This would be similar to how the `cr` and `challenge_rating` fields work. 

Size is defined here on the Monster Model:
https://github.com/open5e/open5e-api/blob/b16e3d12b739eb1801935f2ebc6c90d47029f5b3/api/models/monster.py#L11

**Comment by uribracha2611** [comment]
thanks, so just to be sure, i need to add the representation in open5e-api/api/models/monster.py and i need to add the data itself in monsters.json. do i need to change something in api_v2?

**Comment by uribracha2611** [comment]
also i have found that there is a file Monster.json_SKIPPED, i don't need to change it correct?

**Comment by uribracha2611** [comment]
i have create a pull request that can be seen here [#401](https://github.com/open5e/open5e-api/pull/401)

**Comment by augustjohnson** [comment]
I have an alternative solution to this that covers all approaches in #425

**Comment by uribracha2611** [comment]
It looks great! Does it require any changes to the monster.json?.
