### ISSUE TITLE
Add additional action attributes like reach, damage type and number of targets

### ISSUE THREAD

**Issue by txtsd** [open5e/open5e-api#40]
Currently actions only have the following data in json:  `attack_bonus`, `damage_bonus`, `damage_dice`, `name` and `desc`.

It would be nice to have reach, damage type, and number of targets too so they can be used programmatically. Also, uses per day.

Later on, perhaps, we could have more attributes for `DC_on_hit` and `status_on_fail` for any statuses applied like `diseased`.

Progress:
- [X] reach
- [X] range_normal
- [X] range_max
- [X] damage_type
- [ ] on_hit
- [ ] on_crit
- [ ] multiattacks
- [ ] complex attacks
- [ ] attack bonus with specific weapon

**Comment by augustjohnson** [comment]
I believe the framework in v2 matches the intent of this issue. If there are follow up specific fields, they can be considered in separate items.
https://api-beta.open5e.com/v2/creatures/srd_vampire/
