### ISSUE TITLE
Monster stat block errors for Level Up Advanced 5e Monstrous Menagerie

### ISSUE THREAD

**Issue by dprothero** [open5e/open5e-api#406]
I have noticed some errors in the data for some of the A5E Monstrous Menagerie monsters. Examples:

1. The [Dread Knight Champion](https://open5e.com/monsters/dread-knight-champion-a5e) is missing all of its special reactions (it should have reactions Cold Sacrifice, Deflect, Riposte, and Seal of Silence).
2. The same stat block as well as the [Dread Knight](https://open5e.com/monsters/dread-knight-a5e) are missing a number of apostrophes and commas (e.g. `doesnt`, `immunity to cold necrotic poison and psychic damage`)
3. Also, both Dread Knight stat blocks have an extra "action" ("If the wall enters a creatures space...", also another missing apostrophe). It should just be part of the description for the previous "Ice Wall" action.

These were just a few issues I noticed on these stat blocks. I went poking around and the missing apostrophes/commas issue seems to be pervasive.

**Comment by dprothero** [comment]
Another issue with the same data set:

https://open5e.com/monsters/shadow-elf-champion-warrior-a5e
and
https://open5e.com/monsters/shadow-elf-warrior-a5e

Are both missing the spells under "Shadow Elf Spellcasting". The section is just cut off before showing any spells.

@mshea am I remembering correctly that you loaded the A5E Monstrous Menagerie? Could there have been issues with your data set or script you used?

**Comment by mshea** [comment]
There absolutely could have been.
