### ISSUE TITLE
V2 Environments

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#429]
It's possible we could do both Environments like "swamp" and planes like "material" in a single data type, with a hierarchy. At that point, we can tie creatures to environments, and do things like "Filter by creatures with an environment on the material plane" could result in a reasonable list.

The wizards SRD doesn't give a ton of guidance here, but it gives a bit.
Consider naming the model "places" ? or zones, or realms maybe, or region, or area.

**Comment by Kordishal** [comment]
Considering that it is mostly used for environments that creatures can be found in, I would just keep Environment as the name for the entity. I think this works for "swamp" as well as for "underdark" and "material plane" or "The Nine Hells".
