### ISSUE TITLE
A5e Document Split out

### ISSUE THREAD

**Issue by augustjohnson** [open5e/open5e-api#436]
https://a5esrd.com/a5esrd - this page splits out documents into fairly distinct sections. Adventurer's Guide, Monstrous Menagerie, etc.  I believe those correspond fairly cleanly with the Document concept in Open5e, and should be treated as separate documents.

**Comment by Kordishal** [comment]
Documents and Keys:

Adventurer's Guide - `a5e-ag`
Trials & Treasurers - `a5e-tt`
Monstrous Menagerie - `a5e-mm`
Dungeon's Delver Guide - `a5e-ddg`
Gate Pass Gazette - `a5e-gpg`
Extras - `a5e-ex`

**Comment by Kordishal** [comment]
Created AG, DDG and GPG and sorted the backgrounds into their respective documents.

Next step is to sort out the rest of the A5E SRD v2 entities:

- [ ] Spells
- [ ] Feat

v1 Entities won't be migrated as that wouldn't be worth it.

**Comment by augustjohnson** [comment]
This is fixed with @Kordishal 's commit, which has been merged.
