### ISSUE TITLE
Monsters missing descriptions

### ISSUE THREAD

**Issue by michaeleconomy** [open5e/open5e-api#44]
So in this file: https://github.com/eepMoody/open5e-api/blob/master/data/WOTC_5e_SRD_v5.1/monsters.json

I'd expect it to contain the descriptions for monsters from here:
https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf
(not all monsters have descriptions, but a lot of them do).

In case me or someone else gets motivated to fix this:
Did you generate the JSON file by hand? or by parsing the pdf?

What should the name of the description property be? ("description" is nice and clear, but "desc" is more consistent with the rest of the file).

**Comment by eepMoody** [comment]
I'm not sure I'm seeing which monsters have descriptions. Cursory scrolling through the first half I didn't see _any_. 

As for the text, the original was made by parsing the PDF, but since then it's been extensively hand-edited.

**Comment by eepMoody** [comment]
As for any that are there, I'd want to stick with "desc" for consistency.

**Comment by michaeleconomy** [comment]
So weird - there's only 7 or so, kinda makes you think it was like a copy paste error by wizards.

**Comment by eepMoody** [comment]
Yeah. I notice they're concentrated in the animals/beasts appendix. Maybe
they just did that differently, or are intended to create more for the
other monsters eventually.

**Comment by augustjohnson** [comment]
As of right now, there is no field in the model for "description" of a monster.

"awakened tree" is an example in the SRD that has a short description (after the actions section).

I believe a technical enhancement to store a description at a monster level,would be required, then the corresponding import and data changes to consume the field correctly.

**Comment by augustjohnson** [comment]
And of course, we'd need the actual data.

**Comment by augustjohnson** [comment]
To spec out this work:

- [ ] Identify the total list of creatures that have a description. (These appear to be almost completely concentrated in the Appendx MM-A of the srd).
- [ ] Translate the text descriptions into markdown (it appears as though Bold is about it). 
- [ ] Update the /data/srd/montsters.json document to include a desc field with a markdown.
- [ ] Update the monster importer to pull desc as well.
- [ ] The model should already support this (inheriting it from gamecontent) so the technical step is going to be expose it through the serializer, and maybe adding a filter? Probably adding it to searchindex as well.

**Comment by augustjohnson** [comment]
There's lots of entries in MM-B as well for the NPCs.
- [ ] Add descriptions to docs for NPCs.

**Comment by augustjohnson** [comment]
Here is the total list of slugs of things SRD that have descriptions. 47 items.

Awakened-shrub
Awakened-tree
Axe-beak
Blink-dog
Blood-hawk
Death-dog
Flying-snake
frog
Giant-eagle
Giant-elk
Giant-fire-beetle
Giant-lizard
Giant-owl
Giant-poisonous-snake
Giant-sea-horse
Giant-shark
Giant-spider
Giant-wolf-spider
Hunter-shark
mammoth
mastiff
Phase-spider
quipper
Reef-shark
Winter-wolf
worg
acolyte
archmage
assassin
bandit
Bandit-captain
berserker
commoner
cultist
Cult-fanatic
druid
gladiator
guard
knight
mage
noble
priest
scout
spy
thug
Tribal-warrior
veteran
