### ISSUE TITLE
Add hit dice to sizes model

### ISSUE THREAD

**Issue by aaronsts** [open5e/open5e-api#458]
On page 256 of the SRD you can find the table where the size is linked to a certain dice for monsters.
This is consistent for object as well which you can find on on page 203 in SRD.

**Comment by augustjohnson** [comment]
Hit dice is added on many creatures, but not on many others.

**Comment by augustjohnson** [comment]
Ok to call this done:
1. All monsters should have a value for Hit Dice
2. The "Sizes" model object could have a hit dice value. Perhaps a "resilient multiplier" value as well?
