### ISSUE TITLE
Missing armour

### ISSUE THREAD

**Issue by clivecrous** [open5e/open5e-api#46]
It appears that armour is nowhere available within the API

**Comment by shadowedlucario** [comment]
@clivecrous Check out https://api.open5e.com/sections/. `Armour` is one of the fields in there

**Comment by Gredelston** [comment]
Armor (spelled American-style) is currently available on the API.
Here's the API endpoint for it: https://api.open5e.com/armor/
You can also see it on the website: https://www.open5e.com/sections/armor

I don't have permission to close this issue, but @eepMoody would you please close this obsolete issue?
