### ISSUE TITLE
V2 search breaks when searching for "ring"

### ISSUE THREAD

**Issue by Sturlen** [open5e/open5e-api#467]
https://api-beta.open5e.com/v2/search/?query=ring returns Server Error (500)
It seems to be one particular item as https://api-beta.open5e.com/v2/search/?query=ring&limit=1&page=2 fails, 

seems to be specifically the second item returned, as page=1 and page=3 works

V1 search works as expected, so this is a V2 issue: https://api.open5e.com/search/?text=ring

**Comment by augustjohnson** [comment]
I think there's a hacky solution I put into place to look up the route, and this is causing the issue. I think that the best solution would be for each model to produce it's own route, maybe in some sort of inherited route(self) property.

https://github.com/open5e/open5e-api/blob/staging/api_v2/serializers/search.py#L72 - this is the cruddy lookup.
