### ISSUE TITLE
Add Monsters from Kobold Press's Black Flag

### ISSUE THREAD

**Issue by mshea** [open5e/open5e-api#475]
Attached to this is a zip file containing markdown versions of Kobold Press's Black Flag monsters under the ORC license. Their format is different than other 5e monsters so it might not be the cleanest conversion but I thought I'd help move it in the right direction. 

[black_flag_monsters_markdown.zip](https://github.com/user-attachments/files/16021758/black_flag_monsters_markdown.zip)

**Comment by crhallberg** [comment]
Follow development here: #472

**Comment by crhallberg** [comment]
Thank you for this! I was able to compare action counts to track down as lot of missing formatting issues. In return, here are the markdown files that I corrected in return.

[mshea_blackflag_monsters_markdown.zip](https://github.com/user-attachments/files/16117015/mshea_blackflag_monsters_markdown.zip)

**Comment by augustjohnson** [comment]
So #472 has been merged. I am working on v2 conversion now.
