### ISSUE TITLE
casting_time data is wrong

### ISSUE THREAD

**Issue by tylereed** [open5e/open5e-api#542]
It looks like the data for casting_time in v2 of the spell data is bad.  9 of the spells have a time of 'reaction'.  The rest of them have a casting time of 'action'.

Looking at Misty Step, which should have a casting time of "Bonus Action", the api returns 'action'.

 It seems to me that the converter function `get_casting_time` isn't converting from v1 to v2 properly.

**Comment by augustjohnson** [comment]
This was fixed in #546.
