### ISSUE TITLE
Items returned

### ISSUE THREAD

**Issue by rogueturnip** [open5e/open5e-api#59]
I've looked around the documents a bunch but can't find this, is there a way to limit the number of results returned?  Default is 50 and I wanted to lower this.

Thanks!

**Comment by M-Davies** [comment]
> Limits and Pagination
> You can set how many results you want using /?limit.
> For example, https://api.open5e.com/monsters/?limit=100 will return a paginated set of results with the page size of 100.
> 

From https://open5e.com/api-docs
