### ISSUE TITLE
Write API (Post/Put)

### ISSUE THREAD

**Issue by hugoprudente** [open5e/open5e-api#62]
Hi, 

I have started to use open5e-api to standardise my personal content, to have a centralised awsesome search for all my 5e content. 

With that, I would like to confirm if open5e-api provides any write API so I can Post/Put my OCRed content to the application on my local server?

If not the only way to inject data to the platform is using the .json files using the same pattern?

**Comment by eepMoody** [comment]
Hi @hugoprudente! For safety I can't set up a write API, it would make it way too easy for non-srd content to get in, which would open us up to getting shut down.

If you've got SRD-covered content, you can add a new source JSON to the appropriate folder and make a pull request, though!

**Comment by hugoprudente** [comment]
Hi eepMoody,

I understand it, the idea was not for the public release at all, but only for personal use and internal network deployment only.

Today I have it with a docker-compose on my local machine and I use it to search the SRD+ Some extra that I manual created the json files. 

As I have tons of PDF of bought license content and PDF search is more than horrible, the Open5e api become one of my favorite tools.

With a API would be much easier to post the OCRd content of my PDFs instead going over som json parser/writer file.

And I don't trust platforms as DnDBeyond as if they shutdown I'll never have my content again, so I never buy things on platforms that can break, I prefer to gather all my pdfs and ebook versions myself.

**Comment by eepMoody** [comment]
Ah, I see. I'm not sure how to set that up so it would only work in certain
locations. If you've got a thought on how to pull it off, I'd be happy to
accept a pull request for it though!
