### ISSUE TITLE
API endpoints for Combat and Gameplay Mechanics

### ISSUE THREAD

**Issue by zachanator070** [open5e/open5e-api#73]
From what I can tell there is currently not an API endpoint to get information from the following sections that the front end has:

Combat:
- Actions in Combat
- Attacking
- Combat Sequence
- Cover
- Damage & Healing
- Mounted combat
- Movement in Combat
- Underwater Combat

Gameplay Mechanics:
- Ability Scores
- Between Adventures
- Environment
- Movement
- Objects
- Rest
- Saving Throws
- Time

I imagine this may be as easy as adding each of these sections to data/WOTC_5e_SRD_v5.1/sections.json 

This doesn't sound too hard as it looks like just converting the html you have in the UI to markdown and then adding to the json file. I think I can make a PR but I wanted to ask before I put work into it.

**Comment by augustjohnson** [comment]
This is accurate. As of today, there are a set of markdown files served by the frontend that are not represented on the backend.  they can be found here (for example).
https://github.com/open5e/open5e/tree/master/static/markdown/combat

I think the proposal would basically be to load these into the /sections endpoint as markdown (properly formatted).

There may be some metadata required for proper operation. (for example there's a "feats" section that's distinct from the feats list).
