### ISSUE TITLE
Desert Giant

### ISSUE THREAD

**Issue by InsaneClownGuy** [open5e/open5e-api#85]
Just letting people know that there's a glitch on the Desert Giant entry. There are others and I'm happy to point them out when I find them. 
![2021-03-11 13_50_10-Open5e - Desert Giant](https://user-images.githubusercontent.com/80485617/110847154-30b54200-8272-11eb-8145-690bcb31dfd1.png)

As you can see, Perception is showing as $1. Probably should fix that.

**Comment by paullofte** [comment]
This issue appears to be resolved

<img width="928" alt="image" src="https://user-images.githubusercontent.com/1108419/224190110-b4e77fdd-55b5-4bb5-9961-d5802f5eee29.png">
